Lebensmittel:
  - "MIGROS"
  - "COOP"
  - "DENNER"
  - "ALDI SUISSE"
  - "LIDL SCHWEIZ"
  - "SPAR"
  - "VOLG"

Transport:
  - "SBB"
  - "ZVV"
  - "MOBILITY"
  - "BVB"
  - "UBER"
  - "TAXI"
  - "PARKING"
  - "TANKSTELLE"
  - "AGROLA"
  - "COOP PRONTO"
  - "MIGROL"

Unterhaltung:
  - "NETFLIX"
  - "SPOTIFY"
  - "AMAZON PRIME"
  - "KINO"
  - "PATHÉ"
  - "KITAG"
  - "BLUE"
  - "SWISSCOM"

Fixkosten:
  - "SWISSCOM"
  - "SALT"
  - "SUNRISE"
  - "EWZ"
  - "SERAFE"
  - "MIETE"
  - "KRANKENKASSE"
  - "CSS"
  - "SWICA"
  - "HELSANA"
  - "SANITAS"

Restaurant:
  - "RESTAURANT"
  - "CAFÉ"
  - "BISTRO"
  - "STARBUCKS"
  - "MCDONALD"
  - "BURGER KING"
  - "SUBWAY"
  - "PIZZERIA"

Shopping:
  - "MANOR"
  - "GLOBUS"
  - "JELMOLI"
  - "H&M"
  - "ZARA"
  - "MEDIAMARKT"
  - "INTERDISCOUNT"
  - "GALAXUS"
  - "DIGITEC"

Sport:
  - "MIGROS FITNESS"
  - "ACTIV FITNESS"
  - "BASEFIT"
  - "FITNESS"
  - "SPORTXX"
  - "INTERSPORT"
  - "OCHSNER SPORT"

Gesundheit:
  - "APOTHEKE"
  - "PHARMACY"
  - "DROGERIEN"
  - "ARZT"
  - "ZAHNARZT"
  - "SPITAL"